#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/whyred

PRODUCT_COPY_FILES += \
    vendor/xiaomi/whyred/proprietary/vendor/etc/MIUI_DualCamera_watermark.png:$(TARGET_COPY_OUT_VENDOR)/etc/MIUI_DualCamera_watermark.png \
    vendor/xiaomi/whyred/proprietary/vendor/etc/MIUI_Time.ttf:$(TARGET_COPY_OUT_VENDOR)/etc/MIUI_Time.ttf \
    vendor/xiaomi/whyred/proprietary/vendor/etc/Miui-Light.ttf:$(TARGET_COPY_OUT_VENDOR)/etc/Miui-Light.ttf \
    vendor/xiaomi/whyred/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/xiaomi/whyred/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/xiaomi/whyred/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/xiaomi/whyred/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/xiaomi/whyred/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/xiaomi/whyred/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/xiaomi/whyred/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/xiaomi/whyred/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/xiaomi/whyred/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/female_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_bg.png \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/female_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_icon.png \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/male_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_bg.png \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/male_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_icon.png \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/score_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_bg.png \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/score_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_icon.png \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_imx376_ofilm_global_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_imx376_ofilm_global_i_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_imx376_sunny_global_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_imx376_sunny_global_ii_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_imx486_ofilm_global_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_imx486_ofilm_global_i_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_imx486_qtech_global_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_imx486_qtech_global_ii_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_ov13855_sunny_cn_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_ov13855_sunny_cn_i_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_s5k2l7_ofilm_cn_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_s5k2l7_ofilm_cn_i_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_s5k2l7_qtech_cn_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_s5k2l7_qtech_cn_ii_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_s5k3l8_ofilm_cn_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_s5k3l8_ofilm_cn_ii_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_s5k5e8_ofilm_cn_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_s5k5e8_ofilm_cn_i_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_s5k5e8_ofilm_global_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_s5k5e8_ofilm_global_i_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_s5k5e8_qtech_cn_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_s5k5e8_qtech_cn_ii_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/camera/whyred_s5k5e8_qtech_global_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/whyred_s5k5e8_qtech_global_ii_chromatix.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/permissions/com.fingerprints.extension.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.fingerprints.extension.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/qdcm_calib_data_huaxing_nt36672_fhd_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_huaxing_nt36672_fhd_video_mode_dsi_panel.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/qdcm_calib_data_shenchao_td4310_fhd_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_shenchao_td4310_fhd_video_mode_dsi_panel.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/qdcm_calib_data_tianma_nt36672_fhd_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_tianma_nt36672_fhd_video_mode_dsi_panel.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/qdcm_calib_data_tianma_td4310_fhd_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_tianma_td4310_fhd_video_mode_dsi_panel.xml \
    vendor/xiaomi/whyred/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/whyred/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/whyred/proprietary/vendor/etc/thermal-engine-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-map.conf \
    vendor/xiaomi/whyred/proprietary/vendor/etc/thermal-engine-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-normal.conf \
    vendor/xiaomi/whyred/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/dbmd4_va_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd4_va_fw.bin \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/fpctzappfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b00 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/fpctzappfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b01 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/fpctzappfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b02 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/fpctzappfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b03 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/fpctzappfingerprint.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b04 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/fpctzappfingerprint.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b05 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/fpctzappfingerprint.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b06 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/fpctzappfingerprint.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b07 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/fpctzappfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.mdt \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/goodixfp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b00 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/goodixfp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b01 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/goodixfp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b02 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/goodixfp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b03 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/goodixfp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b04 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/goodixfp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b05 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/goodixfp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b06 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/goodixfp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b07 \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.mdt \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/tas2557_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2557_uCDSP.bin \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/xiaomi/whyred/proprietary/vendor/firmware/voice_amodel.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/voice_amodel.bin \
    vendor/xiaomi/whyred/proprietary/vendor/lib/mibokeh_660_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_660_opencl.bin

PRODUCT_PACKAGES += \
    activity_recognition.sdm660 \
    gatekeeper.sdm660 \
    keystore.sdm660 \
    libsensor1 \
    libsensor_reg \
    libthermalclient \
    libthermalfeature \
    sensors.ssc \
    camera.sdm660 \
    libMiWatermark \
    libSonyIMX376C3RmscLibrary \
    libSonyIMX376KRmscLibrary \
    libXMFD_AgeGender \
    lib_lowlight \
    libactuator_whyred_imx486_ofilm_global_i_dw9714v \
    libactuator_whyred_imx486_qtech_global_ii_dw9714v \
    libactuator_whyred_s5k2l7_ofilm_cn_i_ak7374 \
    libactuator_whyred_s5k2l7_qtech_cn_ii_ak7374 \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_whyred_imx376_ofilm_global_i_common \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_liveshot \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_preview \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_snapshot \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_snapshot_5M \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_snapshot_5M_hht \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_snapshot_downscale \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_snapshot_hht \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_snapshot_upscale \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_video \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_video_default \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_video_face \
    libchromatix_whyred_imx376_ofilm_global_i_cpp_video_weixin \
    libchromatix_whyred_imx376_ofilm_global_i_default_preview_3a \
    libchromatix_whyred_imx376_ofilm_global_i_default_video_3a \
    libchromatix_whyred_imx376_ofilm_global_i_face_video_3a \
    libchromatix_whyred_imx376_ofilm_global_i_flash_cpp_liveshot \
    libchromatix_whyred_imx376_ofilm_global_i_flash_cpp_preview \
    libchromatix_whyred_imx376_ofilm_global_i_flash_cpp_snapshot \
    libchromatix_whyred_imx376_ofilm_global_i_flash_cpp_video \
    libchromatix_whyred_imx376_ofilm_global_i_flash_preview \
    libchromatix_whyred_imx376_ofilm_global_i_flash_preview_3a \
    libchromatix_whyred_imx376_ofilm_global_i_flash_snapshot \
    libchromatix_whyred_imx376_ofilm_global_i_flash_video \
    libchromatix_whyred_imx376_ofilm_global_i_flash_video_3a \
    libchromatix_whyred_imx376_ofilm_global_i_fullsize_preview_3a \
    libchromatix_whyred_imx376_ofilm_global_i_fullsize_video_3a \
    libchromatix_whyred_imx376_ofilm_global_i_postproc \
    libchromatix_whyred_imx376_ofilm_global_i_preview \
    libchromatix_whyred_imx376_ofilm_global_i_snapshot \
    libchromatix_whyred_imx376_ofilm_global_i_video_default \
    libchromatix_whyred_imx376_ofilm_global_i_video_face \
    libchromatix_whyred_imx376_ofilm_global_i_video_weixin \
    libchromatix_whyred_imx376_ofilm_global_i_weixin_video_3a \
    libchromatix_whyred_imx376_sunny_global_ii_common \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_liveshot \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_preview \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_snapshot \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_snapshot_5M \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_snapshot_5M_hht \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_snapshot_downscale \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_snapshot_hht \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_snapshot_upscale \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_video \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_video_default \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_video_face \
    libchromatix_whyred_imx376_sunny_global_ii_cpp_video_weixin \
    libchromatix_whyred_imx376_sunny_global_ii_default_preview_3a \
    libchromatix_whyred_imx376_sunny_global_ii_default_video_3a \
    libchromatix_whyred_imx376_sunny_global_ii_face_video_3a \
    libchromatix_whyred_imx376_sunny_global_ii_flash_cpp_liveshot \
    libchromatix_whyred_imx376_sunny_global_ii_flash_cpp_preview \
    libchromatix_whyred_imx376_sunny_global_ii_flash_cpp_snapshot \
    libchromatix_whyred_imx376_sunny_global_ii_flash_cpp_video \
    libchromatix_whyred_imx376_sunny_global_ii_flash_preview \
    libchromatix_whyred_imx376_sunny_global_ii_flash_preview_3a \
    libchromatix_whyred_imx376_sunny_global_ii_flash_snapshot \
    libchromatix_whyred_imx376_sunny_global_ii_flash_video \
    libchromatix_whyred_imx376_sunny_global_ii_flash_video_3a \
    libchromatix_whyred_imx376_sunny_global_ii_fullsize_preview_3a \
    libchromatix_whyred_imx376_sunny_global_ii_fullsize_video_3a \
    libchromatix_whyred_imx376_sunny_global_ii_postproc \
    libchromatix_whyred_imx376_sunny_global_ii_preview \
    libchromatix_whyred_imx376_sunny_global_ii_snapshot \
    libchromatix_whyred_imx376_sunny_global_ii_video_default \
    libchromatix_whyred_imx376_sunny_global_ii_video_face \
    libchromatix_whyred_imx376_sunny_global_ii_video_weixin \
    libchromatix_whyred_imx376_sunny_global_ii_weixin_video_3a \
    libchromatix_whyred_imx486_ofilm_global_i_bokeh_preview \
    libchromatix_whyred_imx486_ofilm_global_i_bokeh_preview_3a \
    libchromatix_whyred_imx486_ofilm_global_i_bokeh_snapshot \
    libchromatix_whyred_imx486_ofilm_global_i_common \
    libchromatix_whyred_imx486_ofilm_global_i_cpp_hfr_120 \
    libchromatix_whyred_imx486_ofilm_global_i_cpp_hfr_60 \
    libchromatix_whyred_imx486_ofilm_global_i_cpp_hfr_90 \
    libchromatix_whyred_imx486_ofilm_global_i_cpp_liveshot \
    libchromatix_whyred_imx486_ofilm_global_i_cpp_preview \
    libchromatix_whyred_imx486_ofilm_global_i_cpp_snapshot \
    libchromatix_whyred_imx486_ofilm_global_i_cpp_snapshot_hht \
    libchromatix_whyred_imx486_ofilm_global_i_cpp_video \
    libchromatix_whyred_imx486_ofilm_global_i_cpp_video_weixin \
    libchromatix_whyred_imx486_ofilm_global_i_default_preview_3a \
    libchromatix_whyred_imx486_ofilm_global_i_default_video \
    libchromatix_whyred_imx486_ofilm_global_i_default_video_3a \
    libchromatix_whyred_imx486_ofilm_global_i_hfr_120 \
    libchromatix_whyred_imx486_ofilm_global_i_hfr_120_3a \
    libchromatix_whyred_imx486_ofilm_global_i_hfr_60 \
    libchromatix_whyred_imx486_ofilm_global_i_hfr_60_3a \
    libchromatix_whyred_imx486_ofilm_global_i_hfr_90 \
    libchromatix_whyred_imx486_ofilm_global_i_hfr_90_3a \
    libchromatix_whyred_imx486_ofilm_global_i_liveshot \
    libchromatix_whyred_imx486_ofilm_global_i_pano_preview_3a \
    libchromatix_whyred_imx486_ofilm_global_i_postproc \
    libchromatix_whyred_imx486_ofilm_global_i_preview \
    libchromatix_whyred_imx486_ofilm_global_i_snapshot \
    libchromatix_whyred_imx486_ofilm_global_i_video_weixin \
    libchromatix_whyred_imx486_ofilm_global_i_weixin_video_3a \
    libchromatix_whyred_imx486_ofilm_global_i_zsl_preview_3a \
    libchromatix_whyred_imx486_ofilm_global_i_zsl_video_3a \
    libchromatix_whyred_imx486_qtech_global_ii_bokeh_preview \
    libchromatix_whyred_imx486_qtech_global_ii_bokeh_preview_3a \
    libchromatix_whyred_imx486_qtech_global_ii_bokeh_snapshot \
    libchromatix_whyred_imx486_qtech_global_ii_common \
    libchromatix_whyred_imx486_qtech_global_ii_cpp_hfr_120 \
    libchromatix_whyred_imx486_qtech_global_ii_cpp_hfr_60 \
    libchromatix_whyred_imx486_qtech_global_ii_cpp_hfr_90 \
    libchromatix_whyred_imx486_qtech_global_ii_cpp_liveshot \
    libchromatix_whyred_imx486_qtech_global_ii_cpp_preview \
    libchromatix_whyred_imx486_qtech_global_ii_cpp_snapshot \
    libchromatix_whyred_imx486_qtech_global_ii_cpp_snapshot_hht \
    libchromatix_whyred_imx486_qtech_global_ii_cpp_video \
    libchromatix_whyred_imx486_qtech_global_ii_cpp_video_weixin \
    libchromatix_whyred_imx486_qtech_global_ii_default_preview_3a \
    libchromatix_whyred_imx486_qtech_global_ii_default_video \
    libchromatix_whyred_imx486_qtech_global_ii_default_video_3a \
    libchromatix_whyred_imx486_qtech_global_ii_hfr_120 \
    libchromatix_whyred_imx486_qtech_global_ii_hfr_120_3a \
    libchromatix_whyred_imx486_qtech_global_ii_hfr_60 \
    libchromatix_whyred_imx486_qtech_global_ii_hfr_60_3a \
    libchromatix_whyred_imx486_qtech_global_ii_hfr_90 \
    libchromatix_whyred_imx486_qtech_global_ii_hfr_90_3a \
    libchromatix_whyred_imx486_qtech_global_ii_liveshot \
    libchromatix_whyred_imx486_qtech_global_ii_pano_preview_3a \
    libchromatix_whyred_imx486_qtech_global_ii_postproc \
    libchromatix_whyred_imx486_qtech_global_ii_preview \
    libchromatix_whyred_imx486_qtech_global_ii_snapshot \
    libchromatix_whyred_imx486_qtech_global_ii_video_weixin \
    libchromatix_whyred_imx486_qtech_global_ii_weixin_video_3a \
    libchromatix_whyred_imx486_qtech_global_ii_zsl_preview_3a \
    libchromatix_whyred_imx486_qtech_global_ii_zsl_video_3a \
    libchromatix_whyred_ov13855_sunny_cn_i_common \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_ds_chromatix \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_hfr_120 \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_hfr_60 \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_hfr_90 \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_liveshot \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_preview \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_snapshot \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_snapshot_hdr \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_snapshot_hht \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_us_chromatix \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_video \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_video_face \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_video_full \
    libchromatix_whyred_ov13855_sunny_cn_i_cpp_video_weixin \
    libchromatix_whyred_ov13855_sunny_cn_i_default_preview_bu64297 \
    libchromatix_whyred_ov13855_sunny_cn_i_default_video \
    libchromatix_whyred_ov13855_sunny_cn_i_default_video_bu64297 \
    libchromatix_whyred_ov13855_sunny_cn_i_face_video_3a \
    libchromatix_whyred_ov13855_sunny_cn_i_flash_cpp_liveshot \
    libchromatix_whyred_ov13855_sunny_cn_i_flash_cpp_preview \
    libchromatix_whyred_ov13855_sunny_cn_i_flash_cpp_snapshot \
    libchromatix_whyred_ov13855_sunny_cn_i_flash_cpp_video \
    libchromatix_whyred_ov13855_sunny_cn_i_flash_preview \
    libchromatix_whyred_ov13855_sunny_cn_i_flash_preview_3a \
    libchromatix_whyred_ov13855_sunny_cn_i_flash_snapshot \
    libchromatix_whyred_ov13855_sunny_cn_i_flash_video \
    libchromatix_whyred_ov13855_sunny_cn_i_flash_video_3a \
    libchromatix_whyred_ov13855_sunny_cn_i_hfr_120 \
    libchromatix_whyred_ov13855_sunny_cn_i_hfr_120_bu64297 \
    libchromatix_whyred_ov13855_sunny_cn_i_hfr_60 \
    libchromatix_whyred_ov13855_sunny_cn_i_hfr_60_bu64297 \
    libchromatix_whyred_ov13855_sunny_cn_i_hfr_90 \
    libchromatix_whyred_ov13855_sunny_cn_i_hfr_90_bu64297 \
    libchromatix_whyred_ov13855_sunny_cn_i_liveshot \
    libchromatix_whyred_ov13855_sunny_cn_i_postproc \
    libchromatix_whyred_ov13855_sunny_cn_i_preview \
    libchromatix_whyred_ov13855_sunny_cn_i_snapshot \
    libchromatix_whyred_ov13855_sunny_cn_i_snapshot_hdr \
    libchromatix_whyred_ov13855_sunny_cn_i_video_face \
    libchromatix_whyred_ov13855_sunny_cn_i_video_full \
    libchromatix_whyred_ov13855_sunny_cn_i_video_weixin \
    libchromatix_whyred_ov13855_sunny_cn_i_weixin_video_3a \
    libchromatix_whyred_ov13855_sunny_cn_i_zsl_preview_bu64297 \
    libchromatix_whyred_ov13855_sunny_cn_i_zsl_video_bu64297 \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_4k_preview_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_4k_video_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_bokeh_preview \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_bokeh_preview_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_bokeh_snapshot \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_common \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_hfr_120 \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_hfr_60 \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_hfr_90 \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_liveshot \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_preview \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_snapshot \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_snapshot_hdr \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_snapshot_hht \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_video \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_video_4k \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_cpp_video_weixin \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_default_preview_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_default_video_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_hfr_120 \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_hfr_120_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_hfr_60 \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_hfr_60_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_hfr_90 \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_hfr_90_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_pano_preview_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_postproc \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_preview \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_snapshot \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_snapshot_hdr \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_video \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_video_4k \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_video_weixin \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_weixin_video_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_zsl_preview_3a \
    libchromatix_whyred_s5k2l7_ofilm_cn_i_zsl_video_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_4k_preview_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_4k_video_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_bokeh_preview \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_bokeh_preview_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_bokeh_snapshot \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_common \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_hfr_120 \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_hfr_60 \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_hfr_90 \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_liveshot \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_preview \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_snapshot \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_snapshot_hdr \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_snapshot_hht \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_video \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_video_4k \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_cpp_video_weixin \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_default_preview_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_default_video_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_hfr_120 \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_hfr_120_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_hfr_60 \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_hfr_60_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_hfr_90 \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_hfr_90_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_pano_preview_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_postproc \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_preview \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_snapshot \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_snapshot_hdr \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_video \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_video_4k \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_video_weixin \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_weixin_video_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_zsl_preview_3a \
    libchromatix_whyred_s5k2l7_qtech_cn_ii_zsl_video_3a \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_common \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_hfr_120 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_hfr_60 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_hfr_90 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_liveshot \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_preview \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_snapshot \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_snapshot_hdr \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_snapshot_hht \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_video \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_video_face \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_video_full \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_cpp_video_weixin \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_default_preview_ak7345 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_default_video \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_default_video_ak7345 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_face_video_3a \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_flash_cpp_liveshot \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_flash_cpp_preview \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_flash_cpp_snapshot \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_flash_cpp_video \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_flash_preview \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_flash_preview_3a \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_flash_snapshot \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_flash_video \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_flash_video_3a \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_hfr_120 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_hfr_120_ak7345 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_hfr_60 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_hfr_60_ak7345 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_hfr_90 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_hfr_90_ak7345 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_postproc \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_preview \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_snapshot \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_snapshot_hdr \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_video_face \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_video_full \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_video_weixin \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_weixin_video_3a \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_zsl_preview_ak7345 \
    libchromatix_whyred_s5k3l8_ofilm_cn_ii_zsl_video_ak7345 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_a3_default_preview \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_a3_default_video \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_a3_hfr_120 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_a3_hfr_60 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_a3_hfr_90 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_common \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_ds_chromatix \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_hfr_120 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_hfr_60 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_hfr_90 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_liveshot \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_preview \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_snapshot \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_us_chromatix \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_video \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_cpp_video_full \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_default_video \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_hfr_120 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_hfr_60 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_hfr_90 \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_liveshot \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_postproc \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_preview \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_snapshot \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_video_full \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_zsl_preview \
    libchromatix_whyred_s5k5e8_ofilm_cn_i_zsl_video \
    libchromatix_whyred_s5k5e8_ofilm_global_i_a3_default_preview \
    libchromatix_whyred_s5k5e8_ofilm_global_i_a3_default_video \
    libchromatix_whyred_s5k5e8_ofilm_global_i_a3_hfr_120 \
    libchromatix_whyred_s5k5e8_ofilm_global_i_a3_hfr_60 \
    libchromatix_whyred_s5k5e8_ofilm_global_i_a3_hfr_90 \
    libchromatix_whyred_s5k5e8_ofilm_global_i_common \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_ds_chromatix \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_hfr_120 \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_hfr_60 \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_hfr_90 \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_liveshot \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_preview \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_snapshot \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_us_chromatix \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_video \
    libchromatix_whyred_s5k5e8_ofilm_global_i_cpp_video_full \
    libchromatix_whyred_s5k5e8_ofilm_global_i_default_video \
    libchromatix_whyred_s5k5e8_ofilm_global_i_hfr_120 \
    libchromatix_whyred_s5k5e8_ofilm_global_i_hfr_60 \
    libchromatix_whyred_s5k5e8_ofilm_global_i_hfr_90 \
    libchromatix_whyred_s5k5e8_ofilm_global_i_liveshot \
    libchromatix_whyred_s5k5e8_ofilm_global_i_postproc \
    libchromatix_whyred_s5k5e8_ofilm_global_i_preview \
    libchromatix_whyred_s5k5e8_ofilm_global_i_snapshot \
    libchromatix_whyred_s5k5e8_ofilm_global_i_video_full \
    libchromatix_whyred_s5k5e8_ofilm_global_i_zsl_preview \
    libchromatix_whyred_s5k5e8_ofilm_global_i_zsl_video \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_a3_default_preview \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_a3_default_video \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_a3_hfr_120 \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_a3_hfr_60 \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_a3_hfr_90 \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_common \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_ds_chromatix \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_hfr_120 \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_hfr_60 \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_hfr_90 \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_liveshot \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_preview \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_snapshot \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_us_chromatix \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_video \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_cpp_video_full \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_default_video \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_hfr_120 \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_hfr_60 \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_hfr_90 \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_liveshot \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_postproc \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_preview \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_snapshot \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_video_full \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_zsl_preview \
    libchromatix_whyred_s5k5e8_qtech_cn_ii_zsl_video \
    libchromatix_whyred_s5k5e8_qtech_global_ii_a3_default_preview \
    libchromatix_whyred_s5k5e8_qtech_global_ii_a3_default_video \
    libchromatix_whyred_s5k5e8_qtech_global_ii_a3_hfr_120 \
    libchromatix_whyred_s5k5e8_qtech_global_ii_a3_hfr_60 \
    libchromatix_whyred_s5k5e8_qtech_global_ii_a3_hfr_90 \
    libchromatix_whyred_s5k5e8_qtech_global_ii_common \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_ds_chromatix \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_hfr_120 \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_hfr_60 \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_hfr_90 \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_liveshot \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_preview \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_snapshot \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_us_chromatix \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_video \
    libchromatix_whyred_s5k5e8_qtech_global_ii_cpp_video_full \
    libchromatix_whyred_s5k5e8_qtech_global_ii_default_video \
    libchromatix_whyred_s5k5e8_qtech_global_ii_hfr_120 \
    libchromatix_whyred_s5k5e8_qtech_global_ii_hfr_60 \
    libchromatix_whyred_s5k5e8_qtech_global_ii_hfr_90 \
    libchromatix_whyred_s5k5e8_qtech_global_ii_liveshot \
    libchromatix_whyred_s5k5e8_qtech_global_ii_postproc \
    libchromatix_whyred_s5k5e8_qtech_global_ii_preview \
    libchromatix_whyred_s5k5e8_qtech_global_ii_snapshot \
    libchromatix_whyred_s5k5e8_qtech_global_ii_video_full \
    libchromatix_whyred_s5k5e8_qtech_global_ii_zsl_preview \
    libchromatix_whyred_s5k5e8_qtech_global_ii_zsl_video \
    libdepthmapwrapper \
    libflash_pmic \
    libft2vendor \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmibokeh_660 \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_bokeh \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_le2464c_eeprom \
    libmmcamera_le2464c_master_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_rohm_brcg064gwz_3_eeprom \
    libmmcamera_sunny_ov13855_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_whyred_imx376_ofilm_global_i \
    libmmcamera_whyred_imx376_ofilm_global_i_eeprom \
    libmmcamera_whyred_imx376_sunny_global_ii \
    libmmcamera_whyred_imx376_sunny_global_ii_eeprom \
    libmmcamera_whyred_imx486_ofilm_global_i \
    libmmcamera_whyred_imx486_ofilm_global_i_eeprom \
    libmmcamera_whyred_imx486_qtech_global_ii \
    libmmcamera_whyred_imx486_qtech_global_ii_eeprom \
    libmmcamera_whyred_ov13855_sunny_cn_i \
    libmmcamera_whyred_ov13855_sunny_cn_i_eeprom \
    libmmcamera_whyred_s5k2l7_ofilm_cn_i \
    libmmcamera_whyred_s5k2l7_ofilm_cn_i_eeprom \
    libmmcamera_whyred_s5k2l7_qtech_cn_ii \
    libmmcamera_whyred_s5k2l7_qtech_cn_ii_eeprom \
    libmmcamera_whyred_s5k3l8_ofilm_cn_ii \
    libmmcamera_whyred_s5k3l8_ofilm_cn_ii_eeprom \
    libmmcamera_whyred_s5k5e8_ofilm_i \
    libmmcamera_whyred_s5k5e8_ofilm_i_eeprom \
    libmmcamera_whyred_s5k5e8_qtech_ii \
    libmmcamera_whyred_s5k5e8_qtech_ii_eeprom \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libscveBlobDescriptor \
    libscveBlobDescriptor_stub \
    libscveCommon \
    libscveCommon_stub \
    libscveFaceRecognition \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libscvePanorama \
    libscvePanorama_lite \
    libvideoutils \
    libvidhance \
    libvidhance_gyro \
    fingerprint.fpc.default \
    fingerprint.goodix.default \
    libgf_ca \
    libgf_hal \
    libthermalioctl \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    libvendor.goodix.hardware.fingerprint@1.0 \
    FingerprintExtensionService \
    com.fingerprints.extension \
    cnss-daemon \
    sensors.qti \
    thermal-engine
